/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0


# Visualization (only if you built Geant4 with vis)
/vis/open OGL 600x600-0+0
/vis/viewer/setStyle surface
/vis/drawVolume
/vis/scene/add/axes 0 0 0 5 cm
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
/vis/verbose warnings


# GPS defaults: put source at PMT window by default
/gps/pos/type Point
/gps/pos/centre 0 0 -2.7 cm # window is ~2.55 cm in -z, add 0.15 cm margin
/gps/ang/type iso


# Example: Cs-137 (enable one at a time or run separate macros)
#/gps/particle gamma
#/gps/ene/mono 661.657 keV


/run/initialize
#/run/beamOn 10000
